[package]
name = "iron_static_server"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]

[dependencies]
iron = "*"
router = "*"
staticfile = "*"
iron_vhosts = "*"
mount = "*"
toml = "*"
serde = "*"
serde_derive = "*"
