[package]
name = "iron_static_server"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]

[dependencies]
iron = "*"
router = "*"
staticfile = "*"
iron_vhosts = "*"
mount = "*"
toml = "*"
serde = "*"
serde_derive = "*"

[replace]
"iron_vhosts:0.4.0" = { git = 'https://github.com/andete/iron_vhosts', branch = "non_static_config" }

