[package]
name = "iron_static_server"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]

[dependencies]
iron = { version = "*", features = ["ssl"] }
router = "*"
staticfile = "*"
iron_vhosts = "*"
mount = "*"
toml = { version = "*", features = ["serde"], default-features = false }
serde = "*"
serde_derive = "*"
error-chain = "*"
env_logger = "*"
log = "*"

[replace]
"hyper:0.9.14" = { git = 'https://github.com/SergioBenitez/hyper.git', branch = '0.9.x' }
#"iron_vhosts:0.4.0" = { git = 'https://github.com/andete/iron_vhosts', branch = "non_static_config" }
