listen = "0:3000"

[tls]
cert = "cert.pem"
key = "key.pem"

[[vhost]]
hostname = "website1.local"
static_files = "/tmp/website1"

[[vhost]]
hostname = "website2.local"
static_files = "/tmp/website2"


