[listen.tls3001]
address = "0.0.0.0:3001"
tls = { cert = "cert.pem", key = "key.pem" }

[listen.normal3000]
address = "0.0.0.0:3000"

[vhost.website1]
listen = "normal3000"
hostname = "website1.local"
static_files = "website1"

[vhost.website2]
listen = "tls3001"
hostname = "website2.local"
static_files = "website2"

[vhost.website3]
listen = "normal3000"
hostname = "website3.local"
redirect = { host = "www.rust-lang.org", scheme = "https" }
